### ISSUE TITLE
Power Board - I2c error

### ISSUE THREAD

**Issue by glennl** [oresat/oresat-ground-station#13]
When switching power to the Lime SDR, there is a huge disturbance on the I2C bus. This was noticed when command responses were being acted upon. It appears to only be significant when the LimeSDR power is switched.

The disturbance is a -2V and +3V disturbance at about 4 uS. Then there is ringing at about 500 kHz following that.

Photos on Slack...

**Comment by glennl** [comment]
Figure out power board issues
* Power bump
   * Filter; ___No, worsens problem with back-emf___
   * Slow-start; ___Worked quite well, and we think it fixed the problem___
* i2c issue

**Comment by oliver-rew** [comment]
Can we completely isolate the rock64 and maybe even the GPIO expander, from the rest of the board?

**Comment by oliver-rew** [comment]
For powering the GPIO expander, we could either pull power from the rock64, or put an isolated power supply on the board?
